In [1]:
#1. Importa el paquete NUMPY bajo el nombre np.

import numpy as np


In [2]:
#2. Imprime la versión de NUMPY y la configuración.

# Imprimir la versión de NumPy
print("Versión de NumPy:", np.__version__)

# Imprimir la configuración de NumPy
print("\nConfiguración de NumPy:")
print(np.show_config())

Versión de NumPy: 1.23.5

Configuración de NumPy:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lisan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lisan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lisan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lisan/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lisan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lisan/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lisan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]


In [3]:
#3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
# Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

#[tu código aquí]
a = np.random.random((2,3,5))

In [4]:
a = np.random.rand(2, 3, 5)

In [5]:
a = np.random.randn(2, 3, 5)

In [6]:
#4. Imprime a.
a

array([[[ 0.21395334, -0.34925026, -0.30087112,  0.09288076,
          1.4987684 ],
        [ 0.77808134,  0.39428254,  0.9495224 , -0.81511023,
         -1.8999916 ],
        [ 1.10508414, -1.77624784, -1.1024902 ,  1.79578769,
          0.65222096]],

       [[ 0.82040041,  0.02374171,  1.51051392,  0.4210838 ,
          0.98899246],
        [-1.468839  ,  0.75880714, -0.70533263,  0.80477429,
         -0.04879635],
        [-0.80322378,  0.52293103, -0.35686364, -0.55658169,
         -1.14239843]]])

In [7]:
#5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"
b = np.ones((5,2,3))

In [8]:
#6. Imprime b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?
# Verificar si tienen el mismo tamaño (misma forma)
if a.shape == b.shape:
    print("Sí, los arrays tienen el mismo tamaño. Lo demonstramos con la función shape.")
else:
    print("No, los arrays tienen diferente tamaño.Lo demonstramos con la función shape.")

No, los arrays tienen diferente tamaño.Lo demonstramos con la función shape.


In [10]:
#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?
print("No es posible sumar a y b porque tiene formas distintas, como lo podemos verlo abajo:")
a + b

No es posible sumar a y b porque tiene formas distintas, como lo podemos verlo abajo:


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [11]:
#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".
#[tu código aquí]
print("Forma de b:", b.shape)
c = b.transpose(1, 2, 0)  # Transponer las dimensiones en el orden 1, 2, 0

# Verificar las formas de a y c para asegurarnos de que ahora tienen la misma estructura
print("Forma de a:", a.shape)
print("Forma de c:", c.shape)

Forma de b: (5, 2, 3)
Forma de a: (2, 3, 5)
Forma de c: (2, 3, 5)


In [12]:
#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?
d = a + c
print(d)
print('\nAhora sí que funciona porque a y c tienen la misma forma.')

[[[ 1.21395334  0.65074974  0.69912888  1.09288076  2.4987684 ]
  [ 1.77808134  1.39428254  1.9495224   0.18488977 -0.8999916 ]
  [ 2.10508414 -0.77624784 -0.1024902   2.79578769  1.65222096]]

 [[ 1.82040041  1.02374171  2.51051392  1.4210838   1.98899246]
  [-0.468839    1.75880714  0.29466737  1.80477429  0.95120365]
  [ 0.19677622  1.52293103  0.64313636  0.44341831 -0.14239843]]]

Ahora sí que funciona porque a y c tienen la misma forma.


In [13]:
#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

print("Esa es la matriz 'a': \n", a)

print("\nEsa es la matriz 'd': \n", d)
print("\nHay diferencia en términos de valores porque las matriz 'd' es la suma de la matriz 'a' con la 'c'.")

Esa es la matriz 'a': 
 [[[ 0.21395334 -0.34925026 -0.30087112  0.09288076  1.4987684 ]
  [ 0.77808134  0.39428254  0.9495224  -0.81511023 -1.8999916 ]
  [ 1.10508414 -1.77624784 -1.1024902   1.79578769  0.65222096]]

 [[ 0.82040041  0.02374171  1.51051392  0.4210838   0.98899246]
  [-1.468839    0.75880714 -0.70533263  0.80477429 -0.04879635]
  [-0.80322378  0.52293103 -0.35686364 -0.55658169 -1.14239843]]]

Esa es la matriz 'd': 
 [[[ 1.21395334  0.65074974  0.69912888  1.09288076  2.4987684 ]
  [ 1.77808134  1.39428254  1.9495224   0.18488977 -0.8999916 ]
  [ 2.10508414 -0.77624784 -0.1024902   2.79578769  1.65222096]]

 [[ 1.82040041  1.02374171  2.51051392  1.4210838   1.98899246]
  [-0.468839    1.75880714  0.29466737  1.80477429  0.95120365]
  [ 0.19677622  1.52293103  0.64313636  0.44341831 -0.14239843]]]

Hay diferencia en términos de valores porque las matriz 'd' es la suma de la matriz 'a' con la 'c'.


In [14]:
#12. Multiplica a y c. Asigna el resultado a e.

e = a * c
e

array([[[ 0.21395334, -0.34925026, -0.30087112,  0.09288076,
          1.4987684 ],
        [ 0.77808134,  0.39428254,  0.9495224 , -0.81511023,
         -1.8999916 ],
        [ 1.10508414, -1.77624784, -1.1024902 ,  1.79578769,
          0.65222096]],

       [[ 0.82040041,  0.02374171,  1.51051392,  0.4210838 ,
          0.98899246],
        [-1.468839  ,  0.75880714, -0.70533263,  0.80477429,
         -0.04879635],
        [-0.80322378,  0.52293103, -0.35686364, -0.55658169,
         -1.14239843]]])

In [15]:
#13. ¿Es e igual a a? ¿Por qué sí o por qué no?
print("La matriz 'e', resultado de la multiplicación de la matriz 'a' con la matriz 'c', es igual a la matriz 'a' porque la matriz 'c' es formada apenas por ones. Y todos los numeros multiplicados por 1 resulta en si mismo.")

La matriz 'e', resultado de la multiplicación de la matriz 'a' con la matriz 'c', es igual a la matriz 'a' porque la matriz 'c' es formada apenas por ones. Y todos los numeros multiplicados por 1 resulta en si mismo.


In [16]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

d_max = d.max()  
d_min = d.min()
d_mean = d.mean()

print("Valor maximo: ", d_max, "\nValor minimo: ", d_min, "\nValor medio: ", d_mean)

Valor maximo:  2.795787690507114 
Valor minimo:  -0.8999916048172796 
Valor medio:  1.0668609852641562


In [17]:
#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.
print(d.shape) #comprobamos la forma del array d, ya que tenemos que crear un array f con una forma identica

f = np.empty((2,3,5))

(2, 3, 5)


In [18]:
#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
#Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
#Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
#Asigna 0 al valor correspondiente(s) en f para d_min en d.
#Asigna 100 al valor correspondiente(s) en f para d_max en d.
#Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
#Nota: no necesitas usar Numpy en esta pregunta.

# Paso 4: Rellenar f basado en las condiciones dadas
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75


In [22]:
""""
#17. Imprime d y f. ¿Tienes el f esperado? Por ejemplo, si tu d es: array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

   [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
    [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
    [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
Tu f debería ser: array([[[ 75., 75., 75., 25., 75.], [ 75., 75., 25., 25., 25.], [ 75., 25., 75., 75., 75.]],

   [[ 25.,  25.,  25.,  25., 100.],
    [ 75.,  75.,  75.,  75.,  75.],
    [ 25.,  75.,   0.,  75.,  75.]]])
    
"""

#[tu código aquí]
# Imprimir los arrays d y f para ver el resultado
print("Array d:")
print(d)
print("\nArray f:")
print(f)

Array d:
[[[ 1.21395334  0.65074974  0.69912888  1.09288076  2.4987684 ]
  [ 1.77808134  1.39428254  1.9495224   0.18488977 -0.8999916 ]
  [ 2.10508414 -0.77624784 -0.1024902   2.79578769  1.65222096]]

 [[ 1.82040041  1.02374171  2.51051392  1.4210838   1.98899246]
  [-0.468839    1.75880714  0.29466737  1.80477429  0.95120365]
  [ 0.19677622  1.52293103  0.64313636  0.44341831 -0.14239843]]]

Array f:
[[[ 75.  25.  25.  75.  75.]
  [ 75.  75.  75.  25.   0.]
  [ 75.  25.  25. 100.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  25.  25.  25.]]]


In [23]:
print('Sí, el array f tiene el resultado esperado, o sea, sólo apresenta resultados 0, 25, 50, 75 o 100.')

Sí, el array f tiene el resultado esperado, o sea, sólo apresenta resultados 0, 25, 50, 75 o 100.


In [25]:
""""
#18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena 
("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
De nuevo, no necesitas Numpy en esta pregunta.
"""
# Crear un array vacío f con la misma forma que d, pero de tipo string
f = np.empty(d.shape, dtype=str)

# Rellenar f basado en las condiciones dadas
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 'A'
            elif d[i, j, k] == d_max:
                f[i, j, k] = 'E'
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 'C'
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 'B'
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 'D'

# Imprimir los arrays d y f para ver el resultado
print("Array d:")
print(d)
print("\nArray f:")
print(f)

Array d:
[[[ 1.21395334  0.65074974  0.69912888  1.09288076  2.4987684 ]
  [ 1.77808134  1.39428254  1.9495224   0.18488977 -0.8999916 ]
  [ 2.10508414 -0.77624784 -0.1024902   2.79578769  1.65222096]]

 [[ 1.82040041  1.02374171  2.51051392  1.4210838   1.98899246]
  [-0.468839    1.75880714  0.29466737  1.80477429  0.95120365]
  [ 0.19677622  1.52293103  0.64313636  0.44341831 -0.14239843]]]

Array f:
[[['D' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'A']
  ['D' 'B' 'B' 'E' 'D']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'B' 'B' 'B']]]
